### ISSUE TITLE
Access Denied from get_Video_By_Tiktok

### ISSUE THREAD

**Issue by MinghaoXu16** [davidteather/TikTok-Api#374]
Hi, I encountered a problem two days ago and it seemed to be there since then. 
I'm using the latest version (3.7.9 ) and python3.7.
When I tried :
tk=api.getTikTokById(id,custom_did=did,custom_verifyFp=verifyFp)
tiktokData=api.get_Video_By_TikTok(tk,custom_did,custom_verifyFp=verifyFp)

It returns Access Denied.
But when I tried with the tiktok object returns by trending, it works fine.
tk=api.trending(custom_did=did,custom_verifyFp=verifyFp)[0]

I found the problem may related to the downloadAddr it returns.
I can directly access to the url returned by trending and open it with my browser.
But the url returned by getTikTokById is not.
So is the url returned in byHashtag method.

**Comment by ziyueluo** [comment]
I also tried ByUsername() and it does not return valid video downloading address neither

**Comment by leourl** [comment]
same here

**Comment by MinghaoXu16** [comment]
The download address obtained from api.trending(custom_did=did,custom_verifyFp=verifyFp) is different from that obtained from api.getTikTokById(id,custom_did=did,custom_verifyFp=verifyFp). 

The one that works takes the form of "tiktokcdn" followed by a sequence of letters while the one does not work is somehow missing that sequence of letter.

**Comment by davidteather** [comment]
I got no clue why this works but it's currently working for me
```
from TikTokApi import TikTokApi
api = TikTokApi()

v_bytes = api.get_Video_By_TikTok(api.trending()[0])
with open("test.mp4", 'wb') as o:
    o.write(v_bytes
```

**Comment by serenat96** [comment]
Hi David, thank you for your reply!

Have you ever tried getting a tik tok video from a specific hashtag? It does not work for api.get_Video_By_TikTok with the object to be a tik tok retrieved from a hashtag.

**Comment by serenat96** [comment]
Trending works for me as well though.

**Comment by ziyueluo** [comment]
Trending always works. The tik tok returned from the trending list works fine but access was still denied for all tik toks returned from byHashtag and bySound

**Comment by ziyueluo** [comment]
My code is as following:   

n=api.byHashtag('nbadraft',count=5,custom_did=did,custom_verifyFp="verify_2c4c2089b9e3b28c54009a79b927ae98")

tiktokData=api.get_Video_By_TikTok(n[0]，custom_did=did,custom_verifyFp="verify_2c4c2089b9e3b28c54009a79b927ae98")

The result is 
b'<HTML><HEAD>\n<TITLE>**Access Denied**</TITLE>\n</HEAD><BODY>\n<H1>Access Denied</H1>\n \nYou don\'t have permission to access "http&#58;&#47;&#47;v16&#45;web&#46;tiktok&#46;com&#47;video&#47;tos&#47;useast2a&#47;tos&#45;useast2a&#45;pve&#45;0068&#47;41bb9aa443e84ec4aac2e8ac297796b7&#47;&#63;" on this server.<P>\nReference&#32;&#35;18&#46;fa03617&#46;1605939550&#46;35b79142\n</BODY>\n</HTML>\n'

**Comment by ziyueluo** [comment]
Really need help on this. Hope you may have time to fix it soon!! Thank you so much!

I think the problem is that the download address for the trending tik tok objects and the objects returned by a hashtag/ID/sound is different. Here is an example. 

Trending: 'htts://v16m.tiktokcdn.cpom/7e4886a5fd48a51730a84e71bf416b07/5fb907b6/video/tos/useast2a/tos-useast2a-pve-0068/cd576dbb84f04423880b6e0be03e7a36/?a=1233&br=1246&bt=623&cr=0&cs=0&cv=1&dr=0&ds=3&er=&l=202011210627230101890741643E014E82&lr=tiktok_m&mime_type=video_mp4&qs=0&rc=am9pbHlscmZydzMzNDczM0ApN2lmM2hoZWVkNzg1PDxpNWcyZmYxLy1mZ2BfLS1jMTZzczBfNjZiMWAxLjJiM14yMTQ6Yw%3D%3D&vl=&vr='

Others:  'https://v16-web.tiktok.com/video/tos/useast2a/tos-useast2a-pve-0068/41bb9aa443e84ec4aac2e8ac297796b7/?a=1988&br=1830&bt=915&cr=0&cs=0&cv=1&dr=0&ds=3&er=&expire=1605961138&l=202011210618460101890491564B015945&lr=tiktok_m&mime_type=video_mp4&policy=2&qs=0&rc=MzQ3O2tpNWc6eDMzNzczM0ApNzxmNmQ5OTxnNzUzOTk5O2dnYHMvc2JsY25fLS1iMTZzczE1YzE1LjAvXmMyMTFiMC06Yw%3D%3D&signature=c943e0e9ae52002fde21b7858f7d3ce3&tk=tt_webid_v2&vl=&vr='

Did you see that the formats are different? For the trending one, you can click it and open up the video directly but for the others, if you click on it, it would tell you page is having a problem

**Comment by davidteather** [comment]
Fixed in version 3.8.1 at least for me

**Comment by serenat96** [comment]
Mine is still not working. Could I see your code? It still showed access denied to me after I upgraded to v3.8.1

**Comment by davidteather** [comment]
```
t = api.byUsername('therock', did=did, custom_verifyFp='your_verify_fp')[0]
v_bytes = api.get_Video_By_TikTok(t, did=did, custom_verifyFp='your_verify_fp')
with open("test.mp4", 'wb') as o:
    o.write(v_bytes)
```

**Comment by serenat96** [comment]
Thank you David! I got it working! Thank you so much for your effort!
