### ISSUE TITLE
[BUG] - KeyError: 'hasMore'

### ISSUE THREAD

**Issue by hinchyy** [davidteather/TikTok-Api#521]
Well the API has been working fine till last night where I believe there was an update, saw another person with a similar issue but this is the one I am getting.

    if not res["hasMore"] and not first:
KeyError: 'hasMore'

**Comment by AlexGriffith** [comment]
I'm getting the same thing with most API calls I've tried. 
.getUser() is still working fine, but .byUsername()  and .trending() are not.

**Comment by davidteather** [comment]
Should be fixed with [V3.9.2](https://github.com/davidteather/TikTok-Api/releases/tag/V3.9.2)

**Comment by jmaher02** [comment]
Hi!  I have been getting this issue on various projects, I have the updated version but still receiving the same traceback as above. 

`  File "C:\Users\computer\PycharmProjects\tiktokUsers_v2\main.py", line 10, in <module>
    trending = api.trending(count=results, custom_verifyFp="")
  File "C:\Users\computer\AppData\Local\Programs\Python\Python39\lib\site-packages\TikTokApi\tiktok.py", line 341, in trending
    if not res["hasMore"] and not first:
KeyError: 'hasMore'`

**Comment by davidteather** [comment]
You’ll need to provide a custom verifyFp there’s a YouTube video linked in the readme I recommend watching

**Comment by jmaher02** [comment]
> You’ll need to provide a custom verifyFp there’s a YouTube video linked in the readme I recommend watching

Thank you!  Forgot to add to this project, but also learned from your video to update the custom_verifyFp every few hours.
