### ISSUE TITLE
[INSTALLATION] - NotImplementedError

### ISSUE THREAD

**Issue by MartinaGranato** [davidteather/TikTok-Api#988]
I had "This loop is already running" error and I tried:

from TikTokApi import TikTokApi
import nest_asyncio
nest_asyncio.apply()

api = TikTokApi()
for video in api.trending.videos():
    print(video.author.username)

But now the error is: 

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[3], line 4
      1 import nest_asyncio
      2 nest_asyncio.apply()
----> 4 api = TikTokApi()
      5 for video in api.trending.videos():
      6     print(video.author.username)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokApi\tiktok.py:159, in TikTokApi.__init__(self, logging_level, request_delay, custom_device_id, generate_static_device_id, custom_verify_fp, use_test_endpoints, proxy, executable_path, *args, **kwargs)
    156 self.logger.setLevel(logging_level)
    158 with _thread_lock:
--> 159     self._initialize(
    160         request_delay=request_delay,
    161         custom_device_id=custom_device_id,
    162         generate_static_device_id=generate_static_device_id,
    163         custom_verify_fp=custom_verify_fp,
    164         use_test_endpoints=use_test_endpoints,
    165         proxy=proxy,
    166         executable_path=executable_path,
    167         *args,
    168         **kwargs,
    169     )

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokApi\tiktok.py:205, in TikTokApi._initialize(self, **kwargs)
    200     self._custom_device_id = "".join(
    201         random.choice(string.digits) for num in range(19)
    202     )
    204 if self._signer_url is None:
--> 205     self._browser = asyncio.get_event_loop().run_until_complete(
    206         asyncio.gather(browser.create(**kwargs))
    207     )[0]
    209     self._user_agent = self._browser.user_agent
    211 try:

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\nest_asyncio.py:90, in _patch_loop.<locals>.run_until_complete(self, future)
     87 if not f.done():
     88     raise RuntimeError(
     89         'Event loop stopped before Future completed.')
---> 90 return f.result()

File ~\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py:232, in Task.__step(***failed resolving arguments***)
    228 try:
    229     if exc is None:
    230         # We use the `send` method directly, because coroutines
    231         # don't have `__iter__` and `__next__` methods.
--> 232         result = coro.send(None)
    233     else:
    234         result = coro.throw(exc)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\TikTokApi\browser_utilities\browser.py:74, in browser.create(**kwargs)
     71     self.options["executable_path"] = self.executable_path
     73 self._thread_locals = threading.local()
---> 74 self._thread_locals.playwright = await async_playwright().start()
     75 self.playwright = self._thread_locals.playwright
     76 self.browser = await self.playwright.webkit.launch(
     77     args=self.args, **self.options
     78 )

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py:51, in PlaywrightContextManager.start(self)
     50 async def start(self) -> AsyncPlaywright:
---> 51     return await self.__aenter__()

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py:46, in PlaywrightContextManager.__aenter__(self)
     44 if not playwright_future.done():
     45     playwright_future.cancel()
---> 46 playwright = AsyncPlaywright(next(iter(done)).result())
     47 playwright.stop = self.__aexit__  # type: ignore
     48 return playwright

File ~\AppData\Local\Programs\Python\Python310\lib\asyncio\futures.py:201, in Future.result(self)
    199 self.__log_traceback = False
    200 if self._exception is not None:
--> 201     raise self._exception
    202 return self._result

File ~\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py:232, in Task.__step(***failed resolving arguments***)
    228 try:
    229     if exc is None:
    230         # We use the `send` method directly, because coroutines
    231         # don't have `__iter__` and `__next__` methods.
--> 232         result = coro.send(None)
    233     else:
    234         result = coro.throw(exc)

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py:247, in Connection.run(self)
    244 async def init() -> None:
    245     self.playwright_future.set_result(await self._root_object.initialize())
--> 247 await self._transport.connect()
    248 self._init_task = self._loop.create_task(init())
    249 await self._transport.run()

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py:132, in PipeTransport.connect(self)
    130 except Exception as exc:
    131     self.on_error_future.set_exception(exc)
--> 132     raise exc
    134 self._output = self._proc.stdin

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py:120, in PipeTransport.connect(self)
    117     if getattr(sys, "frozen", False):
    118         env.setdefault("PLAYWRIGHT_BROWSERS_PATH", "0")
--> 120     self._proc = await asyncio.create_subprocess_exec(
    121         str(self._driver_executable),
    122         "run-driver",
    123         stdin=asyncio.subprocess.PIPE,
    124         stdout=asyncio.subprocess.PIPE,
    125         stderr=_get_stderr_fileno(),
    126         limit=32768,
    127         creationflags=creationflags,
    128         env=env,
    129     )
    130 except Exception as exc:
    131     self.on_error_future.set_exception(exc)

File ~\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py:218, in create_subprocess_exec(program, stdin, stdout, stderr, limit, *args, **kwds)
    215 loop = events.get_running_loop()
    216 protocol_factory = lambda: SubprocessStreamProtocol(limit=limit,
    217                                                     loop=loop)
--> 218 transport, protocol = await loop.subprocess_exec(
    219     protocol_factory,
    220     program, *args,
    221     stdin=stdin, stdout=stdout,
    222     stderr=stderr, **kwds)
    223 return Process(transport, protocol, loop)

File ~\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py:1652, in BaseEventLoop.subprocess_exec(self, protocol_factory, program, stdin, stdout, stderr, universal_newlines, shell, bufsize, encoding, errors, text, *args, **kwargs)
   1650     debug_log = f'execute program {program!r}'
   1651     self._log_subprocess(debug_log, stdin, stdout, stderr)
-> 1652 transport = await self._make_subprocess_transport(
   1653     protocol, popen_args, False, stdin, stdout, stderr,
   1654     bufsize, **kwargs)
   1655 if self._debug and debug_log is not None:
   1656     logger.info('%s: %r', debug_log, transport)

File ~\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py:493, in BaseEventLoop._make_subprocess_transport(self, protocol, args, shell, stdin, stdout, stderr, bufsize, extra, **kwargs)
    489 async def _make_subprocess_transport(self, protocol, args, shell,
    490                                      stdin, stdout, stderr, bufsize,
    491                                      extra=None, **kwargs):
    492     """Create subprocess transport."""
--> 493     raise NotImplementedError

NotImplementedError: 

 - OS: [e Windows 10]
 - TikTokApi Version [5.2.2] -
I am running code on Jupyter Notebook. Can anyone help me?
@davidteather

**Comment by terrok9** [comment]
Hello!
You should run all your code on another IDE. Jupyter Notebook is not optimal for this library. Use Spyder/VSCode instead.

If you insist on using Jupyter Notebook:

You should install and import some libraries to meet some requirements. For example, try:

`import nest_asyncio
nest_asyncio.apply()`

before running anything else.

**Comment by josemarichal** [comment]
FYI.. I got the same exact error when I ran it in Sypder instead of Jupyter NB

**Comment by terrok9** [comment]
Did you solve the error?

**Comment by davidteather** [comment]
Should be fixed in V6 I think?

**Comment by BenOnAir** [comment]
Even with this method it's still showing the NotImplementedError
![image](https://github.com/davidteather/TikTok-Api/assets/33434052/e594f3df-9843-4b54-a269-63e9d668e992)
